Development Complete
daashandayo/design-teardown pull request #1
Opened 2019-03-11 16:03 UTC by daashandayo

2019-03-11 16:27 UTC, inhaq requested changes
### Good work 👏🏻
Code looks clean 💯
Few things to take care of. First, need to clear the floats. Also, there should be columns of 25%, 25%, 50% in a row. 
Kindly do these tweaks and resubmit for review.

2019-03-11 16:50 UTC, daashandayo commented
It'd be helpful if you let us know where to add a row with columns of 25%, 25% & 50%

2019-03-11 16:54 UTC, inhaq commented
> @inhaq It'd be helpful if you let us know where to add a row with columns of 25%, 25% & 50%

You can also do 33% and 66%. Kindly add it to the bottom. of the current site.

2019-03-12 09:43 UTC, daashandayo commented on assets/css/main.css
> +    clear: left;
@inhaq  Cleared Float, although we did not understand why we needed to do it as we are using fixed height containers.

2019-03-12 09:44 UTC, daashandayo commented on index.html
> +  <!-- ARTICLES WITH ADS -->
Added a section with 25%, 25% & 50% width columns.

2019-03-12 09:47 UTC, inhaq commented on assets/css/main.css
> +    clear: left;
@daashandayo when you apply floats, it needs to be cleared in every scenario. If you don't clear it, your parent element will be broken and in the older browser, it'll not look the same as you're seeing it in your up to date browsers. Hopefully, this will make sense now.

2019-03-12 10:32 UTC, inhaq requested changes
[This](https://snag.gy/e5OnBs.jpg) is how broken div looks like, and after a fix like [this](https://snag.gy/iSPBJ5.jpg). Need to fix it for `LATEST ARTICLES SECTION` and `ARTICLES WITH ADS`. [This](https://css-tricks.com/all-about-floats/) great resource will help you understand about floats.

2019-03-12 11:18 UTC, daashandayo commented
> [This](https://snag.gy/e5OnBs.jpg) is how broken div looks like, and after a fix like [this](https://snag.gy/iSPBJ5.jpg). Need to fix it for `LATEST ARTICLES SECTION` and `ARTICLES WITH ADS`. [This](https://css-tricks.com/all-about-floats/) great resource will help you understand about floats.

Thanks for that, now we understood why we needed to do `clearfix`.

2019-03-12 11:21 UTC, daashandayo commented on assets/css/main.css
> +.clearfix:after {
Added `.clearfix` class to all parent elements with floated child.

2019-03-12 12:08 UTC, inhaq approved these changes
### 👍🏻for this project
Well done guys, go ahead and submit a project completion form. Good luck with the next ones 🎉

2019-03-12 13:20 UTC, merged

2019-03-12 13:20 UTC, daashandayo commented
> ### 👍🏻for this project
> Well done guys, go ahead and submit a project completion form. Good luck with the next ones 🎉

Thank You :)